In [1]:
import numpy as np


# create a 4x4 matrix with False values
matrix = np.full((4, 4), False)
matrix

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [7]:
import numpy as np

# create a list of random integers to 100
digits = np.random.randint(-100, 100, size=100)
odd_digits = np.array([])

for i in range(len(digits)):
    if digits[i] % 2 != 0:
        odd_digits = np.append(odd_digits, digits[i])

print(digits)
print(odd_digits)

[  79   39   62   43   90  -42  -99  -51   30   34   31   71    8   -8
   37   28   18   66   57   -2   89  -32  -81  -66   88  -79   55   56
   36  -75   89  -54  -34  -44  -54    0 -100   68  -22   44   66   87
   22   53   81  -82   66   45   65  -79  -35   14  -13   22   66  -48
   44   32  -40   78   -9   58   59    9   62   60  -27   43   97  -79
   71   46  -53   98  -81   60  -80  -75  -52    2  -14  -16   89   90
  -90  -92   66   97   33 -100   -6   35   25   70    3  -10   -4  -49
  -67   52]
[ 79.  39.  43. -99. -51.  31.  71.  37.  57.  89. -81. -79.  55. -75.
  89.  87.  53.  81.  45.  65. -79. -35. -13.  -9.  59.   9. -27.  43.
  97. -79.  71. -53. -81. -75.  89.  97.  33.  35.  25.   3. -49. -67.]


In [24]:
import numpy as np

digits = np.random.randint(0, 100, size=20)

for i in range(len(digits)):
    if digits[i] % 2 != 0:
        digits[i] = -1

print(digits)

[80 -1 44 20 -1 76 54 14 28 12 28 80 -1 -1 74 92 10 -1 -1 -1]


In [ ]:
import numpy as np

matrix_a = np.random.randint(0, 100, size=(5, 1))
print(matrix_a)

matrix_b = np.random.randint(0, 100, size=(5, 1))
print(matrix_b)

concat_matrix = np.concatenate((matrix_a, matrix_b), axis=1)
print(concat_matrix)

[[25]
 [18]
 [14]
 [51]
 [29]]
[[24]
 [84]
 [70]
 [33]
 [30]]
[[25 24]
 [18 84]
 [14 70]
 [51 33]
 [29 30]]


In [31]:
import numpy as np

matrix_a = np.random.randint(0, 100, size=(5, 1))
print(matrix_a)

matrix_b = np.random.randint(0, 100, size=(5, 1))
print(matrix_b)

concat_matrix = np.concatenate((matrix_a, matrix_b), axis=0)

print(concat_matrix)

[[29]
 [69]
 [57]
 [99]
 [77]]
[[31]
 [72]
 [20]
 [92]
 [19]]
[[29]
 [69]
 [57]
 [99]
 [77]
 [31]
 [72]
 [20]
 [92]
 [19]]


In [33]:
import numpy as np

# create a list of random integers to 100
digits = np.random.randint(-100, 100, size=100)

for i in range(len(digits)):
    if digits[i] in range(0, 10):
        print(digits[i])

5
7
7
4
2
5
2
